site_name: Color Project Docs
nav:
    - Installation: index.md
    - ColorCLI: colorcli.md
    - ColorDaemon: colord.md
    - Faucet: faucet.md
    - Explorer: Explorer_setup.md
    - JoinTestNet: joinTestNet.md
    - ChangeValidatorLogo: ChangeMonikerLogo.md
    - Ledger Nano Setup: ledgersetup.md
theme: material


